development:
  adapter: mysql2
  database: app_development
  username: marianainguanzo
  password: password1
  socket: /tmp/mysql.sock #mac
#  socket: /var/run/mysqld/mysqld.sock   #Linux

test:
  adapter: mysql2
  database: app_test
  username: marianainguanzo
  password: password1
  socket: /tmp/mysql.sock #mac
#  socket: /var/run/mysqld/mysqld.sock   #Linux

production:
  adapter: mysql2
  database: app
  username: marianainguanzo
  password: password1
#  socket: /tmp/mysql.sock #mac
  socket: /var/lib/mysql/mysql.sock
#  socket: /tmp/mysql.sock   #hm
